import { PushNotificationIOS } from "react-native";

export default Object.freeze({
  REGISTER: "Register",
  LOGIN: "Login",
  RESET_PASSWORD: "ResetPassword",
  OTP: "otp",
  NEW_PASSWORD: "NewPassword",
  HOME: "Home",
  MENU: "Menu",
  MENUSCREEN: "MenuScreen",
  MENUSTACK: "MenuStack",
  SUBMENU: "SubMenu",
  SUBMENUSCREEN: "SubMenuScreen",
  SUBMENUSTACK: "SubMenuStack",
  MENUDETAILS: "MenuDetails",
  OFFERS: "Offers",
  PROFILE: "Profile",
  MORE: "More",
  MORESCREEN: "MoreScreen",
  PAYMENTDETAILS: "Payment Details",
  ORDERS: "My Orders",
  ORDERSHOME: "Orders Home",
  NOTIFICATION: "Notification",
  INBOX: "Inbox",
  ABOUTUS: "About Us",
  CHECKOUT: "Checkout",
  ADDRESS: "Address",
});
